### ISSUE TITLE
Add docs for symfony 4 path

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluThemeBundle#12]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | no
| Bundle Version | -
| Sulu Version | -
| Browser Version | -

#### Expected Behavior

```yaml
liip_theme:
    themes: ['default']
    active_theme: 'default'
    load_controllers: false
    assetic_integration: false
    path_patterns:
        app_resource:
            - '%kernel.project_dir%/templates/themes/%%current_theme%%/%%template%%'
```
